spring:
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

  session:
    timeout:
      seconds: 9000
server:
  port: 0
kafka:
  bootstrapAddress: localhost:9092
  topic:
    ready-for-game: READY
    invite-to-a-game: INVITE
    move: MOVE

---
spring:
  profiles: A
server:
  port: 8081

---
spring:
  profiles: B
server:
  port: 8082
