spring:
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
server:
  port: 0
kafka:
  bootstrapAddress: localhost:9092
  topic:
    ready-for-game: READY
    invite-to-a-game: INVITE
    move: MOVE

---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: A
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: B
